//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FcoMgr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FcoDBEntities : DbContext
    {
        public FcoDBEntities()
            : base("name=FcoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<UpgradeResult> UpgradeResults { get; set; }
        public virtual DbSet<MainUAL> MainUALs { get; set; }
        public virtual DbSet<FcoList> FcoLists { get; set; }
        public virtual DbSet<FCO> FCOes { get; set; }
    }
}
