//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FcoMgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainUAL
    {
        public string Id { get; set; }
        public string ShippedSystemSerialNo { get; set; }
        public string MaintainedSystemSerialNo { get; set; }
        public string CountryName { get; set; }
        public string UpgradeCode { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<int> CompletionStat { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string FCONo { get; set; }
        public string FCORev { get; set; }
    }
}
