//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FcoMgr
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpgradeResult
    {
        public string Id { get; set; }
        public string SystemSerialNo { get; set; }
        public string UpgradeCode { get; set; }
        public string ModelNumber { get; set; }
        public Nullable<int> CompletionStat { get; set; }
    }
}
